nhsee/config/urls.py
from django.contrib import admin
#from django.contrib.auth import views as auth_views
from django.urls import path, include
# from django.conf.urls import url
#from .views import HomeListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scoring.urls')),
    # url(r'^', include('scoring.urls')),
    #path('login/', auth_views.login),
    #path('', HomeListView.as_view(), name='home'),
]

nhsee/scoring/urls.py
from django.urls import path
from django.conf.urls import url
import scoring.views
from scoring.views import *
from scoring.views.remove_all_data import remove_all_data
from scoring.views.display.display_top_projects import display_top_projects
from scoring.views.display.display_welcome import welcome
from scoring.views.calc_sort.calculate_scores import calculate_scores
from scoring.views.display.display_unassignedjudge import display_unassignedjudge
from scoring.views.display.display_unassignedproject import display_unassignedproject
from scoring.views.display.display_unassigned import display_unassigned
from scoring.views.display.unassigned_judgeassignment import display_unasigned, createjudgeassignment

#from .views import HomeListView

urlpatterns = [
    # url(r'add/score/$', add_score, name='add_score'),
    # url(r'^edit/$', edit_score, name='edit_score'),
    path('', welcome, name = 'welcome'),
    path('add_score/', add_score, name='add_score'),
    path('display_judges/', display_judges, name='display_judges'),
    path('display_projects/', display_projects, name='display_projects'),
    path('display_judge_assignments/', display_judge_assignments, name='display_judge_assignments'),
    path('display_students/', display_students, name='display_students'),
    path('import_file/', import_file, name='import_file'),
    path('export_judge_assignment/', export_judge_assignment, name='export_judge_assignment'),
    path('export_project/', export_project, name='export_project'),
    path('remove_all_data/', remove_all_data, name='remove_all_data'),
    path('calculate_scores/', calculate_scores, name='calculate_scores'),
    path('assigned', createjudgeassignment, name = "assigned_judge"),
    path('display_top_projects/', display_top_projects, name='display_top_projects'),
    path('display_unassignedjudge/', display_unassignedjudge, name='display_unassignedjudge'),
    path('display_unassignedproject/', display_unassignedproject, name='display_unassignedproject'),
    path('display_unassigned/', display_unassigned, name='display_unassigned'),
    path('unassigned-judgeassignment/', display_unasigned, name='unassigned-judgeassignment'),


]

nhsee/scoring/models/Judge.py
from django.db import models

class Judge(models.Model):
    judge_id = models.CharField(primary_key=True, max_length=5)
    name = models.CharField(max_length=10)

    def __str__(self):
        return '%s' %self.judge_id

nhsee/scoring/models/Judge_Assignment.py
from django.db import models
from scoring.models.Judge import Judge
from scoring.models.Project import Project

class Judge_Assignment(models.Model):
    ja_id = models.IntegerField(primary_key=True)
    judge_id = models.ForeignKey(Judge, on_delete=models.CASCADE)
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)
    goal_score = models.IntegerField(null=True)
    plan_score = models.IntegerField(null=True)
    action_score = models.IntegerField(null=True)
    result_analysis_score = models.IntegerField(null=True)
    communication_score = models.IntegerField(null=True)
    raw_score = models.IntegerField(null=True)
    z_score = models.FloatField(null=True)
    rank = models.FloatField(null=True)

    def __str__(self):
        return self.judge_id.judge_id + " " + self.project_id.project_id

nhsee/scoring/models/Project.py
from django.db import models

class Project(models.Model):
    project_id = models.CharField(primary_key=True, max_length=6)
    table_id = models.IntegerField(null=True)
    description = models.CharField(max_length=1000)
    project_title = models.CharField(max_length=500)
    project_category = models.CharField(max_length=100)
    avg_score = models.FloatField(null=True)
    rank = models.IntegerField(null=True)
    z_score = models.FloatField(null=True)
    z_score_rank = models.IntegerField(null=True)
    avg_01 = models.FloatField(null=True)
    avg_01_rank = models.IntegerField(null=True)
    scaled_score = models.FloatField(null=True)
    scaled_rank = models.FloatField(null=True)
    scaled_z = models.FloatField(null=True)
    isef_score = models.FloatField(null=True)
    isef_rank = models.IntegerField(null=True)
    category_rank = models.IntegerField(null=True)
    fair_rank = models.IntegerField(null=True)


    def __str__(self):
        return self.project_id + " : " + self.project_title

nhsee/scoring/models/Student.py
from django.db import models
from scoring.models.Project import Project

class Student(models.Model):
    id = models.CharField(max_length=30, primary_key=True)
    #first_name = models.CharField()
    #last_name = models.CharField()
    #full_name = models.CharField(max_length = 300)
    school = models.CharField(max_length=100)
    project_id = models.ForeignKey(Project, to_field='project_id', on_delete=models.CASCADE)

nhsee/scoring/forms/scoring_form.py
from django.forms import ModelForm
from scoring.models import Judge_Assignment
from scoring.views.calc_sort.calculate_scores import update_scores

class ScoringForm(ModelForm):
    class Meta:
        model = Judge_Assignment
        fields = ['project_id', 'judge_id', 'goal_score', 'plan_score', 'action_score', 'result_analysis_score', 'communication_score','raw_score']

    def save(self, commit=True):

        ja = super(ScoringForm, self).save(commit=False)

        ja.goal_score = self.cleaned_data['goal_score']
        ja.plan_score = self.cleaned_data['plan_score']
        ja.action_score = self.cleaned_data['action_score']
        ja.result_analysis_score = self.cleaned_data['result_analysis_score']
        ja.communication_score = self.cleaned_data['communication_score']
        ja.raw_score = self.cleaned_data['raw_score']
        exja = Judge_Assignment.objects.get(project_id = ja.project_id
                                                ,judge_id = ja.judge_id)

        print(ja.project_id)
        print(ja.judge_id)
        print(exja)
        ja.ja_id = exja.ja_id
        print(ja.ja_id)
        if commit:
            ja.save()
            update_scores()

        return ja

nhsee/scoring/views/convertStrToNum.py
def float1(n):
    if n is None:
        return None
    return float(n)

def int1(n):
    if n is None:
        return None
    return int(n)

nhsee/scoring/views/export_judge_assignment.py
import csv
from scoring.models import Judge_Assignment
from scoring.models import Project
from django.http import HttpResponse

def export_judge_assignment(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="judge_assignments.csv"'

    writer = csv.writer(response)
    writer.writerow(['Judge ID', 'Project ID', 'goal score', 'plan_score', 'action score', 'result Analyis score', 'communication score',  'Raw Score', 'z_score', 'rank' ])

    jas = Judge_Assignment.objects.all().values_list('judge_id', 'project_id', 'goal_score', 'plan_score', 'action_score', 'result_analysis_score',  'communication_score', 'raw_score', 'z_score', 'rank' )
    for ja in jas:
        writer.writerow(list(ja))

    return response


def export_project(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="projects.csv"'

    writer = csv.writer(response)
    writer.writerow(['project_id', 'table_id', 'project_title', 'project_category', 'avg_score', 'rank', 'z_score', 'z_score_rank', 'avg_01', 'avg_01_rank', 'scaled_score', 'scaled_rank', 'scaled_z', 'isef_score', 'isef_rank', 'category_rank', 'fair_rank'  ])

    projs = Project.objects.all().values_list('project_id', 'table_id', 'project_title', 'project_category', 'avg_score', 'rank', 'z_score', 'z_score_rank', 'avg_01', 'avg_01_rank', 'scaled_score', 'scaled_rank', 'scaled_z', 'isef_score', 'isef_rank', 'category_rank', 'fair_rank' )
    for proj in projs:
        writer.writerow(list(proj))

    return response

nhsee/scoring/views/home.py
from django.views.generic import ListView
from scoring.models import *
from django.shortcuts import render

class HomeListView(ListView):
    model = Judge
    template_name = 'home.html'

def home(request):
    return render(request, 'home.html')
    #return render(ListView, 'home.html')

    #def import_db(request):
    #    f = open('Open Scoring UNH Ver09.csv', 'r')
    #    for line in f:
    #        line = line.split(',')
    #        tmp = Judge.object.create()
    #        tmp.judge_id = line[]

nhsee/scoring/views/remove_all_data.py
from scoring.models import *
from django.shortcuts import render

def remove_all_data(request):
    Judge.objects.all().delete()
    Project.objects.all().delete()
    Student.objects.all().delete()
    Judge_Assignment.objects.all().delete()
    return render(request, 'home.html')

nhsee/scoring/templates/assigned.html
{% extends 'base.html' %}
    {% block content %}
    <div align="center">
        <h2 allign:center>Assignment of judge-assignment</h2>
    </div>
        <form action= "assigned_judge"  method="POST">
            {% csrf_token %}
            <table style="width: 70%;" align='center'>
              <label for="unassigned_judges">unassigned judges:</label><br>
              <input list="unassigned_judges" id="judge" name="judge" maxlength="100" required>
                  <datalist id="unassigned_judges">
                      {% if unassigned_judges %}
                          {% for judge in unassigned_judges %}
                              <option value="{{ judge.judge_id }}">
                          {% endfor %}
                      {% else %}
                          <option value="No records">
                      {% endif %}
                  </datalist>
              <br>
              <br>
              <br>
              <label for="unassigned_projects">unassigned_projects:</label><br>

              <input list="unassigned_projects" id="project" name="project" maxlength="100" required>
                  <datalist id="unassigned_projects">
                      {% if unassigned_projects %}
                          {% for project in unassigned_projects %}
                              <option value="{{ project.project_id }}">
                          {% endfor %}
                      {% else %}
                          <option value="No records">
                      {% endif %}
                  </datalist>
              <br><br>
              <button type="submit" formaction="/assigned">Create</button>

        </form>

    {% endblock content %}

nhsee/scoring/templates/base.html
<!-- templates/base.html -->
{% load static %}
<html>
    <head>
        <title>NHSEE</title>
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" rel="stylesheet">
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
    </head>

    <body>

        <header>
            <div class="nav-left">
                    <a href="{% url 'welcome' %}" id="logo">NHSEE</a>
                    <a href="{% url 'display_judges'  %}" role="button" class="b"> Judge </a>
                    <a href="{% url 'display_students' %}" role="button" class="b"> Student </a>
                    <a href="{% url 'display_projects' %}" role="button" class="b"> Project </a>
                    <a href="{% url 'display_judge_assignments' %}" role="button" class="b"> Judge Assignment </a>
                    <a href="{% url 'import_file' %}" role="button" class="b"> Import File </a>
                    <a href="{% url 'export_judge_assignment' %}" role="button" class="b" >Export Judge Assignment</a>
                    <a href="{% url 'export_project' %}" role="button" class="b" >Export Project</a>
                    <a href="{% url 'remove_all_data' %}" role="button" class="b" >Remove All Data</a>
                    <a href="{% url 'add_score' %}" role="button" class="b" >Scoring</a>
                    <a href="{% url 'display_top_projects' %}" role="button" class="b" >Top Projects</a>
                    <a href="{% url 'display_unassignedjudge'  %}" role="button" class="b"> UnassignedJudge </a>
                    <a href="{% url 'display_unassignedproject'  %}" role="button" class="b"> UnassignedProject </a>
                    <a href="{% url 'display_unassigned'  %}" role="button" class="b"> Unassigned </a>
                    <a href="{% url 'unassigned-judgeassignment'  %}" role="button" class="b"> Assignment </a>


            </div>
        </header>
        <div id="content">
            {% block content %}
            {% endblock content%}
        </div>

    </body>
</html>

nhsee/scoring/templates/home.html
{% extends 'base.html' %}
    {% block content %}
        <script src="/static/sorttable.js"></script>
        <script src="/static/filterRecords.js"></script>
    {% if button == "projects" %}
      <input id="searchByProjectId" type="text" placeholder="Search by project ID" name="search">
      {% endif %}

    {% if button == "judges" %}
      <input id="searchByJudgeId" type="text" placeholder="Search by judge ID" name="search">
    {% endif %}

    {% if button == "students" %}
      <input id="searchByStudentId" type="text" placeholder="Search by student ID" name="search">
    {% endif %}

    {% if button == "judge_assignments" %}
      <input id="searchByJudge_Id" type="text" placeholder="Search by judge ID" name="search">
      <input id="searchByProject_Id" type="text" placeholder="Search by project ID" name="search">
    {% endif %}

    {% if button == "unassignedJudge" %}
      <input id="searchByJudgeId" type="text" placeholder="Search by judge ID" name="search">
    {% endif %}
    {% if button == "unassignedProject" %}
      <input id="searchByProjectId" type="text" placeholder="Search by project ID" name="search">
    {% endif %}

        <table class="sortable" id="table" style="text-align:center;" cellspacing="10">
            {% if button == "judges" %}
            <h3>Judges</h3>
            <thead>
                <tr class="item">
                    <th>Judge ID</th>
                    <th>Judge name</th>
                    <th>Status</th>
                    <th>Number of Projects Judged</th>
                </tr>
            </thead>
            {% endif %}
            {% if button == "unassignedJudge" %}
            <h3> Unassigned Judges</h3>
            <thead>
                <tr>
                    <th>Judge ID</th>
                    <th>Judge name</th>
                </tr>
            </thead>
            {% endif %}
            {% if button == "unassignedProject" %}
            <h3> Unassigned Project</h3>
            <thead>
                <tr>
                    <th>Project ID</th>
                    <th>Project title</th>
                </tr>
            </thead>
            {% endif %}
            {% if button == "students" %}
            <h3>Students</h3>
            <thead>
                <tr>
                    <th>Student ID</th>
                    <th>School</th>
                    <th>Project ID</th>
                </tr>
            </thead>
            {% endif %}
            {% if button == "projects" %}
            <h3>Projects</h3>
            <thead>
                <tr>
                    <th>Project ID</th>
                    <th>Table ID </th>
                    <th>Project Title</th>
                    <th>Project Category</th>
                    <th>avg Score</th>
                    <th>Rank</th>
                    <th>Z Score</th>
                    <th>Z Score Rank</th>
                    <th>Average 0-1</th>
                    <th>Average 0-1 Rank</th>
                    <th>Scaled Score</th>
                    <th>Scaled Z</th>
                    <th>Scaled Rank</th>
                    <th>ISEF Score</th>
                    <th>ISEF Rank</th>
                    <th>Category Rank</th>
                    <th>Fair Rank</th>
                    <th> Status</th>
                    <th> number of judges graded</th>
                </tr>
            </thead>
            {% endif %}
            {% if button == "judge_assignments" %}
            <h3>Judge Assignments</h3>
            <thead>
                <tr>
                    <th>Index</th>
                    <th>Judge ID</th>
                    <th>Project ID</th>
                    <th>Goal Score</th>
                    <th>Plan Score</th>
                    <th>Action Score</th>
                    <th>Result Analyis Score</th>
                    <th>Communication Score</th>
                    <th>Raw Score</th>
                    <th>Z Score</th>
                    <th>Rank Score</th>
                </tr>
            </thead>
            {% endif %}
            {% if button == "top_projects" %}
            <h3>Top Projects</h3>
            <thead>
                <tr>
                    <th>Project ID</th>
                    <th>Project Title</th>
                    <th>Project Category</th>
                    <th>Category Rank</th>
                    <th>Fair Rank</th>
                    <th>Student Names</th>
                </tr>
            </thead>
            {% endif %}


            <tbody>
                {% for judge in judge_list %}
                <tr class="judge">
                    <td>{{judge.judge_id}}</td>
                    <td>{{judge.judge_name}}</td>
                    {% if judge.graded != judge.projects_assigned %}
                    <td bgcolor="#FF0000">  </td>
                    {% else %}
                    <td bgcolor="#00FF00"> </td>
                    {% endif %}
                    <td>{{judge.graded}}  / {{judge.projects_assigned}}</td>
                </tr>
                {% endfor %}

                {% for unjudge in unassigned_judges %}
                <tr class="item">
                    <td>{{unjudge.judge_id}}</td>
                    <td>{{unjudge.judge_name}}</td>
                </tr>
                {% endfor %}


                {% for student_item in student_items %}
                <tr class="item">
                    <td>{{student_item.pk}}</td>
                    <td>{{student_item.school}}</td>
                    <td>{{student_item.project_id.project_id}}</td>
                </tr>
                {% endfor %}
                {% for project in project_list %}
                <tr class="item">
                  <td>{{project.project_id}}</td>
                  <td>{{project.table_id}} </td>
                  <td>{{project.project_title}}</td>
                  <td>{{project.project_category}}</td>
                  <td>{{project.avg_score|floatformat:2}}</td>
                  <td>{{project.rank}}</td>
                  <td>{{project.z_score|floatformat:3}}</td>
                  <td>{{project.z_score_rank}}</td>
                  <td>{{project.avg_01|floatformat:3}}</td>
                  <td>{{project.avg_01_rank}}</td>
                  <td>{{project.scaled_score|floatformat:3}}</td>
                  <td>{{project.scaled_z|floatformat:3}}</td>
                  <td>{{project.scaled_rank|floatformat:3}}</td>
                  <td>{{project.isef_score|floatformat:3}}</td>
                  <td>{{project.isef_rank}}</td>
                  <td>{{project.category_rank}}</td>
                  <td>{{project.fair_rank}}</td>
                  {% if project.graded != project.judges_assigned %}
                  <td bgcolor="#FF0000">  </td>
                  {% else %}
                  <td bgcolor="#00FF00"> </td>
                  {% endif %}
                  <td>{{project.graded}}  / {{project.judges_assigned}}</td>
                </tr>
                {% endfor %}
                {% for unproject in unassigned_projects %}
                <tr class="item">
                  <td>{{unproject.project_id}}</td>
                  <td>{{unproject.project_title}}</td>
                </tr>
                {% endfor %}
                {% for ja_item in ja_items %}
                <tr class="item">
                    <td>{{ja_item.pk}}</td>
                    <td>{{ja_item.judge_id.judge_id}}</td>
                    <td>{{ja_item.project_id.project_id}}</td>
                    <td>{{ja_item.goal_score}}</td>
                    <td>{{ja_item.plan_score}}</td>
                    <td>{{ja_item.action_score}}</td>
                    <td>{{ja_item.result_analysis_score}}</td>
                    <td>{{ja_item.communication_score}}</td>
                    <td>{{ja_item.raw_score}}</td>
                    <td>{{ja_item.z_score|floatformat:3}}</td>
                    <td>{{ja_item.rank|floatformat:2}}</td>
                </tr>
                {% endfor %}
                {% for top in top_all_list %}
                <tr class="item">
                    <td>{{top.project_id}}</td>
                    <td>{{top.project_title}}</td>
                    <td>{{top.project_category}}</td>
                    <td>{{top.category_rank}}</td>
                    <td>{{top.fair_rank}}</td>
                    <td>{{top.student_names}}</td>
                    <td>{{top.school_name}}</td>
                </tr>
                {% endfor %}
                {% for top_all_category in top_all_categories %}
                <tr>
                    <td></td>
                    <td style="text-align:left;">
                        <h2>{{top_all_category.0.project_category}}</h2>
                    </td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                    {% for top in top_all_category %}
                    <tr class="item">
                        <td>{{top.project_id}}</td>
                        <td>{{top.project_title}}</td>
                        <td>{{top.project_category}}</td>
                        <td>{{top.category_rank}}</td>
                        <td>{{top.fair_rank}}</td>
                        <td>{{top.student_names}}</td>
                        <td>{{top.school_name}}</td>
                    </tr>
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    {% endblock content %}

nhsee/scoring/templates/import.html
{% extends 'base.html' %}
    {% block content %}
    <div style="height:90vh;">
        <h3>Import File</h3>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="document">
                <button type="submit"> Import </button>
            </form>
    </div>
{% endblock content %}

nhsee/scoring/templates/scoring.html
{% extends 'base.html' %}
    {% block content %}
    <div align="center">
        <h2 allign:center>Project Scoring</h2>
    </div>
        <form method="POST">
            {% csrf_token %}
            <table style="width: 70%;" align='center'>
            <tr>
                <td><h3>Judge Id</h3></td>
                <td>
                {{ form.judge_id }}
                </td>
            </tr>
            <tr>
                <td><h3>Project Id  </h3></td>
                <td>
                {{ form.project_id }}
                </td>
            </tr>
            <tr>
                <td><h3>Scores</h3></td>
                <td>
                <table style="width: 100%; max-width: 800px; table-layout: fixed;">
                    <tr>
                        <td><h4>Category</h4></td>
                        <td><h4>Points possible</h4></td>
                        <td><h4>Points earned</h4></td>
                    </tr>
                    <tr>
                        <td>Goal</td>
                        <td>10</td>
                        <td>{{ form.goal_score }}</td>
                    </tr>
                    <tr>
                        <td>Plan</td>
                        <td>20</td>
                        <td>{{ form.plan_score }}</td>
                    </tr>
                    <tr>
                        <td>Action</td>
                        <td>20</td>
                        <td>{{ form.action_score }}</td>
                    </tr>
                    <tr>
                        <td>Results and Analysis</td>
                        <td>25</td>
                        <td>{{ form.result_analysis_score }}</td>
                    </tr>
                    <tr>
                        <td>
                            Communication
                            <br>
                            Notebook(s) 10
                            <br>
                            Poster       5
                            <br>
                            Interview   10
                        </td>
                        <td>25</td>
                        <td>{{ form.communication_score }}</td>

                    </tr>

                    <tr>
                    <td>Total</td>
                    <td><button onclick="myFunction()">Calculate Total score</button></td>
                    <td> {{ form.raw_score}} </td>
                    <!-- <td><p id="result"></p></td> -->
                    </tr>


            </table>

            <script>

                function goal() {
                var a = document.getElementById("id_goal_score");
                a.setAttribute("min", 0);
                a.setAttribute("max", 10);
                }

                function plan() {
                var b = document.getElementById("id_plan_score");
                b.setAttribute("min", 0);
                b.setAttribute("max", 20);
                }

                function action() {
                var c = document.getElementById("id_action_score");
                c.setAttribute("min", 0);
                c.setAttribute("max", 20);
                }

                function analysis() {
                var d = document.getElementById("id_result_analysis_score");
                d.setAttribute("min", 0);
                d.setAttribute("max", 25);
                }

                function communication() {
                var e = document.getElementById("id_communication_score");
                e.setAttribute("min", 0);
                e.setAttribute("max", 25);
                }

            function myFunction() {
            var a = parseInt(document.getElementById("id_goal_score").value);
            var b = parseInt(document.getElementById("id_plan_score").value);
            var c = parseInt(document.getElementById("id_action_score").value);
            var d = parseInt(document.getElementById("id_result_analysis_score").value);
            var e = parseInt(document.getElementById("id_communication_score").value);

            var x = a + b + c + d +e;
            document.getElementById("id_raw_score").value = x;
            }

            var judgeProjects = [];
            var allProjects = [];
            function sortProjectBasedOnJudge() {
                goal();
                plan();
                action();
                analysis();
                communication();
                var judgeElement =  document.getElementById("id_judge_id");
                var projectElement =  document.getElementById("id_project_id");
                allProjects = getAllProjects(projectElement);
                judgeElement.onchange = function(){
                    var projects = getProjectsBasedOnJudge(judgeElement.value);
                    filterProjects(projects)
                };

                {% for ja_item in ja_items %}
                  var judgeProject = {
                      id: '{{ja_item.id}}',
                      project_id: '{{ja_item.project_id.project_id}}',
                      judge_id: '{{ja_item.judge_id.judge_id}}'
                  }
                  judgeProjects.push(judgeProject);
                {% endfor %}
            }

            function getProjectsBasedOnJudge(judge_id){
                var projects = [];
                for(var i=0; i< judgeProjects.length; i++){
                    if(judgeProjects[i].judge_id == judge_id)
                    {
                        projects.push(judgeProjects[i].project_id);
                    }
                }
                return projects;
            }

            function getAllProjects(projectElement){
                var allProjs = [];
                for(var i=0; i< projectElement.options.length; i++){
                    var project = {
                        value: projectElement.options[i].value,
                        text: projectElement.options[i].text
                    }
                    allProjs.push(project);
                }
                return allProjs;
            }

            function filterProjects(filterdProjects) {
                var fillProjDetails = [];
                for(var i=0; i< filterdProjects.length; i++){
                    for(var j=0; j < allProjects.length; j++){
                        if(filterdProjects[i] == allProjects[j].value){
                            fillProjDetails.push({
                                value: allProjects[j].value,
                                text: allProjects[j].text
                            })
                            break;
                        }
                    }
                }

                var projectElement =  document.getElementById("id_project_id");
                var length = projectElement.options.length;;
                for(var i=1; i< length; i++){
                    projectElement.options.remove(1);
                }
                for(var i=0; i< fillProjDetails.length; i++){
                    var option = document.createElement("option");
                    option.text = fillProjDetails[i].text;
                    option.value = fillProjDetails[i].value;
                    projectElement.options.add(option, (i+1));
                }
            }

            window.onload = sortProjectBasedOnJudge;

            </script>
            <tr>
                <td></td>
                <td>
                    <div align='center'>

                    <input type="submit" value="Save" style="width: 10%; max-width: 100px;">
                    </div>
                </td>
            </tr>
        </form>




    {% endblock content %}

nhsee/scoring/templates/unassignedjudge.html
{% extends 'base.html' %}
    {% block content %}
        <script src="/static/sorttable.js"></script>
        <script src="/static/filterRecords.js"></script>
          <input id="searchByJudgeId" type="text" placeholder="Search by judge ID" name="search">
          <table class="sortable" id="table" style="text-align:center;" cellspacing="10">
            <h3> Unassigned Judges</h3>
            <thead>
                <tr>
                    <th>Judge ID</th>
                    <th>Judge name</th>
                </tr>
            </thead>
            <tbody>
            {% for unjudge in unassigned_judges %}
            <tr class="item">
                <td>{{unjudge.judge_id}}</td>
                <td>{{unjudge.judge_name}}</td>
            </tr>
            {% endfor %}
          </tbody>
      </table>
  {% endblock content %}